import Navbar from '@/components/web/Navbar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function WebGroupLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark overflow-hidden'>
      <body className={inter.className + ` flex flex-col h-screen justify-between`}>
        <Navbar />
        <div className='h-screen w-screen'>
          {children}
        </div>
      </body>
    </html>
  )
}
